title: David Discovers Drug Disovery
author: 
   name: Jitao David Zhang
   email: mail@jdzhang.me
description: >- 
    Notes of a computational biologist working in drug discovery 

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jdzhang.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Accio
twitter_username: AccioThatTweets

theme: minima
minima:
  date_format: "%Y-%m-%d"
  social_links:
    github: Accio
    twitter: AccioThatTweets

comments: true
show_excerpts: true

header_pages:
  - _pages/about.md
  - _pages/publications.md
  - _pages/software.md
  - _pages/education.md

paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

disqus:
  shortname: jdzhang-me

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts

include: ["_pages"]
